# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6ffc8effa2b6f88c481ceb338b1ad5a2f7c4c425b952c4d2046a686297244f1b80eb778e5aa9808da74a9fd665b9b45173f641539dc29b279301e09ffb0f1be

test:
  secret_key_base: ea6022f727250c2b92248da7d1acea33efb1e288c4f21eedcd2a8515a9991e1eafe30b65e17ada61f4ca2f9793a0a6d6cbe0a391acf4e819f08ea134df3331aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
